### ISSUE TITLE
Add readme/license files

### ISSUE THREAD

**Issue by luqmaan** [open-austin/data-portal-analysis#1]
Please add:
- [x] README.md: README template https://github.com/open-austin/sporkability#readme-template
- [x] LICENSE.md: We recommend some sort of public domain license like the Unlicense or CC0.
- [x] CONTRIBUTING.md: For example https://github.com/open-austin/austin-park-equity/blob/master/CONTRIBUTING.md

**Comment by haileypate** [comment]
all three have been added, will create new issues to strengthen them as needed
