### ISSUE TITLE
using ipython notebook...?

### ISSUE THREAD

**Issue by haileypate** [open-austin/data-portal-analysis#3]
I've used the notebooks on my own computer, but I've never collaborated with others on projects using iPython notebooks. 

@mtb33, do you have any quick pointers for me? If I've cloned this repo to my local machine, can I just start a notebook and open the notebook file you've created and it will just work? 

any tips on best practices with checkpoints?

**Comment by mtb33** [comment]
The notebook file in commit 151b69c will work as-is: there are no dependencies.
As for checkpoints, we should probably avoid tracking them altogether; I should have been more careful with my initial commit. I rarely use them.

**Comment by haileypate** [comment]
@mtb33 how do i reach you by email? =) 
hailey.pate@austintexas.gov
