### ISSUE TITLE
snapshot_date_time column should capture what?

### ISSUE THREAD

**Issue by haileypate** [open-austin/data-portal-analysis#6]
@mtb33 on second thought... i think this field should reflect the date/time that the data was retrieved from the portal. since we don't have the retrieval automated yet, let's just put our best guess. we're going to need a sense of the "freshness" during analysis

if we need to also track the timestamp for csv creation (likely to be helpful for testing...) i'd recommend appending an additional column with that info

**Comment by mtb33** [comment]
@haileypate No problem. What format should be used for the CSV creation timestamp?

**Comment by haileypate** [comment]
this is what i've been using in other projects: `2015-10-02T00:00:00`

**Comment by mtb33** [comment]
Closing issue with commit e543e98:
- Timestamps are now in ISO format
- A column for CSV creation time has been added
